### ISSUE TITLE
MySQL Database Character

### ISSUE THREAD

**Issue by dkd-dobberkau** [ksjogo/platformsh-typo3-template#8] opened 2016-09-27 15:11 UTC
In the reports module there is a warning on:
"MySQL Database Character Set 	Wrong value detected
Your default database uses character set "latin1", but only "utf8" or "utf8mb4" is supported with TYPO3."
Can you check if you can influence this?

**Comment by bmack** [comment] 2016-10-25 08:48
Duplicate of https://github.com/platformsh/platformsh-example-typo3/issues/1

**Comment by ksjogo** [comment] 2016-10-25 09:56
Closing here.

**Closed by ksjogo** 2016-10-25 09:56 UTC
